import React, { useState, useEffect } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Checkbox } from '@/components/ui/checkbox'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { X, Edit2, Save, Plus } from 'lucide-react'
import { type Source } from '@/hooks/useSourcesForSelection'

const STORAGE_KEY = 'qhhFormData'

export interface QuotedHousehold {
  id?: string
  zip_code: string
  product_lines: string[]
  lines_quoted: number
  is_bundle: boolean
  quoted_premium: number
  lead_source_id: string
  current_carrier?: string | null
  lead_id?: string | null
  qcn?: string | null
  notes?: string | null
  quick_action_status: string
  opted_into_hearsay: boolean
  items_sold?: number | null
}

const QUICK_ACTION_OPTIONS = [
  'Attempted Contact',
  'Bad Lead',
  'Not Interested – Recycle', 
  'Not Interested Now',
  'Quoted',
  'ReQuote/X-Date',
  'SOLD'
]

const PRODUCT_LINE_OPTIONS = [
  'Standard Auto',
  'Home',
  'Landlords',
  'Renters',
  'Motorcycle',
  'Manufactured Home',
  'Boat',
  'Umbrella',
  'Condominium'
]

const CURRENT_CARRIER_OPTIONS = [
  // National Carriers
  'State Farm',
  'Geico',
  'Progressive',
  'Allstate',
  'Liberty Mutual',
  'Farmers',
  'Nationwide',
  'Travelers',
  'American Family',
  'USAA',
  // Regional (AL/GA)
  'Auto-Owners',
  'Southern Farm Bureau',
  'Georgia Farm Bureau',
  'Alabama Farm Bureau',
  'Alfa Insurance',
  'Mercury',
  'National General',
  'Safeco',
  'The General',
  'Kemper',
  // Other
  'Other Regional Carrier',
  'No Prior Insurance',
  'Unknown/Not Disclosed'
]

const getStatusColor = (status: string): string => {
  switch (status) {
    case 'SOLD': return 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300'
    case 'Quoted': return 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-300'
    case 'ReQuote/X-Date': return 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-300'
    case 'Not Interested – Recycle': return 'bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-300'
    case 'Bad Lead': return 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300'
    default: return 'bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-300'
  }
}

interface QuotedHouseholdFormProps {
  quotedHouseholds: QuotedHousehold[]
  onAdd: (qhh: QuotedHousehold) => void
  onEdit: (index: number, qhh: QuotedHousehold) => void
  onDelete: (index: number) => void
  sources: Source[]
  totalQHH: number
  canEdit: boolean
}

export const QuotedHouseholdForm: React.FC<QuotedHouseholdFormProps> = ({
  quotedHouseholds,
  onAdd,
  onEdit,
  onDelete,
  sources,
  totalQHH,
  canEdit
}) => {
  const [showForm, setShowForm] = useState(false)
  const [editingIndex, setEditingIndex] = useState<number | null>(null)
  const [formData, setFormData] = useState<QuotedHousehold>({
    lead_id: '',
    qcn: '',
    zip_code: '',
    product_lines: [],
    lines_quoted: 0, // For display only, auto-generated by DB
    is_bundle: false, // For display only, auto-generated by DB
    quoted_premium: 0,
    lead_source_id: '',
    current_carrier: '',
    quick_action_status: '',
    items_sold: undefined,
    notes: '',
    opted_into_hearsay: false
  })
  const [errors, setErrors] = useState<Record<string, string>>({})

  // Load from sessionStorage on mount (only for new quotes)
  useEffect(() => {
    if (editingIndex === null && !showForm) {
      try {
        const savedData = sessionStorage.getItem(STORAGE_KEY)
        if (savedData) {
          const parsed = JSON.parse(savedData)
          
          // Restore form data if it exists
          if (parsed.lead_id !== undefined) setFormData(prev => ({ ...prev, lead_id: parsed.lead_id }))
          if (parsed.qcn !== undefined) setFormData(prev => ({ ...prev, qcn: parsed.qcn }))
          if (parsed.zip_code !== undefined) setFormData(prev => ({ ...prev, zip_code: parsed.zip_code }))
          if (parsed.product_lines) setFormData(prev => ({ ...prev, product_lines: parsed.product_lines }))
          if (parsed.quoted_premium !== undefined) setFormData(prev => ({ ...prev, quoted_premium: parsed.quoted_premium }))
          if (parsed.lead_source_id) setFormData(prev => ({ ...prev, lead_source_id: parsed.lead_source_id }))
          if (parsed.current_carrier) setFormData(prev => ({ ...prev, current_carrier: parsed.current_carrier }))
          if (parsed.quick_action_status) setFormData(prev => ({ ...prev, quick_action_status: parsed.quick_action_status }))
          if (parsed.items_sold !== undefined) setFormData(prev => ({ ...prev, items_sold: parsed.items_sold }))
          if (parsed.notes) setFormData(prev => ({ ...prev, notes: parsed.notes }))
          if (parsed.opted_into_hearsay !== undefined) setFormData(prev => ({ ...prev, opted_into_hearsay: parsed.opted_into_hearsay }))
          
          // Auto-open the form if there's saved data
          if (canEdit) {
            setShowForm(true)
          }
        }
      } catch (error) {
        console.error('Failed to load QHH form data from sessionStorage:', error)
      }
    }
  }, [editingIndex, showForm, canEdit])

  // Save to sessionStorage when formData changes (only for new quotes)
  useEffect(() => {
    if (editingIndex === null && showForm) {
      try {
        const dataToSave = {
          lead_id: formData.lead_id,
          qcn: formData.qcn,
          zip_code: formData.zip_code,
          product_lines: formData.product_lines,
          quoted_premium: formData.quoted_premium,
          lead_source_id: formData.lead_source_id,
          current_carrier: formData.current_carrier,
          quick_action_status: formData.quick_action_status,
          items_sold: formData.items_sold,
          notes: formData.notes,
          opted_into_hearsay: formData.opted_into_hearsay,
          timestamp: new Date().toISOString()
        }
        sessionStorage.setItem(STORAGE_KEY, JSON.stringify(dataToSave))
      } catch (error) {
        console.error('Failed to save QHH form data to sessionStorage:', error)
      }
    }
  }, [formData, editingIndex, showForm])

  const resetForm = () => {
    // Clear sessionStorage when form is reset
    try {
      sessionStorage.removeItem(STORAGE_KEY)
    } catch (error) {
      console.error('Failed to clear sessionStorage:', error)
    }
    
    setFormData({
      lead_id: '',
      qcn: '',
      zip_code: '',
      product_lines: [],
      lines_quoted: 0, // For display only, auto-generated by DB
      is_bundle: false, // For display only, auto-generated by DB
      quoted_premium: 0,
      lead_source_id: '',
      current_carrier: '',
      quick_action_status: '',
      items_sold: undefined,
      notes: '',
      opted_into_hearsay: false
    })
    setErrors({})
    setShowForm(false)
    setEditingIndex(null)
  }

  const validateForm = (): boolean => {
    const newErrors: Record<string, string> = {}
    
    // Validate lead_id (required, alphanumeric)
    if (!formData.lead_id || !formData.lead_id.trim()) {
      newErrors.lead_id = 'Lead ID is required'
    } else if (!/^[a-zA-Z0-9]+$/.test(formData.lead_id.trim())) {
      newErrors.lead_id = 'Lead ID must be alphanumeric (letters and numbers only)'
    }
    
    // Validate qcn (required, max 100 characters)
    if (!formData.qcn || !formData.qcn.trim()) {
      newErrors.qcn = 'QCN is required'
    } else if (formData.qcn.trim().length > 100) {
      newErrors.qcn = 'QCN must be 100 characters or less'
    }
    
    // Validate zip_code (5 digits)
    if (!formData.zip_code || !/^\d{5}$/.test(formData.zip_code)) {
      newErrors.zip_code = 'Valid 5-digit zip code is required'
    }
    
    // Validate product_lines
    if (formData.product_lines.length === 0) {
      newErrors.product_lines = 'At least one product line is required'
    }
    
    // Validate quoted_premium (must be positive)
    if (!formData.quoted_premium || formData.quoted_premium <= 0) {
      newErrors.quoted_premium = 'Quoted premium is required and must be greater than 0'
    }
    
    // Validate lead_source_id
    if (!formData.lead_source_id) {
      newErrors.lead_source_id = 'Lead source is required'
    }
    
    // Validate current_carrier
    if (!formData.current_carrier) {
      newErrors.current_carrier = 'Current carrier is required'
    }
    
    // Validate quick_action_status
    if (!formData.quick_action_status) {
      newErrors.quick_action_status = 'Quick action status is required'
    }
    
    // Validate items_sold when status is SOLD
    if ((formData.quick_action_status ?? '').toUpperCase() === 'SOLD') {
      if (!formData.items_sold || formData.items_sold < 1) {
        newErrors.items_sold = 'Items sold is required for SOLD status'
      }
    }
    
    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = () => {
    if (!validateForm()) return

    if (editingIndex !== null) {
      onEdit(editingIndex, formData)
    } else {
      onAdd(formData)
      // Clear sessionStorage after successfully adding new quote
      try {
        sessionStorage.removeItem(STORAGE_KEY)
      } catch (error) {
        console.error('Failed to clear sessionStorage:', error)
      }
    }
    resetForm()
  }

  const startEdit = (index: number) => {
    // Clear any saved draft when editing an existing quote
    try {
      sessionStorage.removeItem(STORAGE_KEY)
    } catch (error) {
      console.error('Failed to clear sessionStorage:', error)
    }
    
    setFormData(quotedHouseholds[index])
    setEditingIndex(index)
    setShowForm(true)
  }

  const toggleProductLine = (line: string) => {
    setFormData(prev => ({
      ...prev,
      product_lines: prev.product_lines.includes(line)
        ? prev.product_lines.filter(l => l !== line)
        : [...prev.product_lines, line]
    }))
  }

  return (
    <div className="form-section">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-lg font-semibold">
          Quoted Households ({quotedHouseholds.length} of {totalQHH} entered)
        </h3>
        {canEdit && !showForm && (
          <Button 
            type="button" 
            variant="outline" 
            size="sm"
            onClick={() => setShowForm(true)}
            disabled={quotedHouseholds.length >= totalQHH}
          >
            <Plus className="h-4 w-4 mr-1" />
            Add QHH
          </Button>
        )}
      </div>

      {/* QHH Entry Form */}
      {showForm && canEdit && (
        <Card className="mb-4">
          <CardHeader>
            <CardTitle className="text-base">
              {editingIndex !== null ? 'Edit' : 'Add'} Quoted Household
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Lead ID - REQUIRED */}
                <div className="space-y-2">
                  <Label htmlFor="lead-id">Lead ID *</Label>
                  <Input
                    id="lead-id"
                    value={formData.lead_id}
                    onChange={(e) => setFormData(prev => ({ ...prev, lead_id: e.target.value }))}
                    placeholder="9-digit Lead Manager ID"
                  />
                  {errors.lead_id && <p className="text-sm text-destructive">{errors.lead_id}</p>}
                </div>

                {/* QCN - REQUIRED */}
                <div className="space-y-2">
                  <Label htmlFor="qcn">QCN *</Label>
                  <Input
                    id="qcn"
                    value={formData.qcn}
                    onChange={(e) => setFormData(prev => ({ ...prev, qcn: e.target.value }))}
                    placeholder="Quote Control Number"
                  />
                  {errors.qcn && <p className="text-sm text-destructive">{errors.qcn}</p>}
                </div>

                {/* Zip Code - REQUIRED */}
                <div className="space-y-2">
                  <Label htmlFor="zip-code">Zip Code *</Label>
                  <Input
                    id="zip-code"
                    value={formData.zip_code}
                    onChange={(e) => {
                      const value = e.target.value.replace(/\D/g, '').slice(0, 5)
                      setFormData(prev => ({ ...prev, zip_code: value }))
                    }}
                    placeholder="12345"
                    maxLength={5}
                  />
                  {errors.zip_code && <p className="text-sm text-destructive">{errors.zip_code}</p>}
                </div>

                {/* Quoted Premium - REQUIRED */}
                <div className="space-y-2">
                  <Label htmlFor="quoted-premium">Quoted Premium *</Label>
                  <Input
                    id="quoted-premium"
                    type="number"
                    step="0.01"
                    min={0}
                    value={formData.quoted_premium}
                    onChange={(e) => setFormData(prev => ({ ...prev, quoted_premium: parseFloat(e.target.value) || 0 }))}
                    placeholder="0.00"
                  />
                  {errors.quoted_premium && <p className="text-sm text-destructive">{errors.quoted_premium}</p>}
                </div>

                {/* Lead Source - REQUIRED */}
                <div className="space-y-2">
                  <Label>Lead Source *</Label>
                  <Select 
                    value={formData.lead_source_id} 
                    onValueChange={(value) => setFormData(prev => ({ ...prev, lead_source_id: value }))}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select source" />
                    </SelectTrigger>
                    <SelectContent>
                      {sources.map(source => (
                        <SelectItem key={source.id} value={source.id}>{source.name}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  {errors.lead_source_id && <p className="text-sm text-destructive">{errors.lead_source_id}</p>}
                </div>

                {/* Current Carrier - REQUIRED */}
                <div className="space-y-2">
                  <Label>Current Carrier *</Label>
                  <Select 
                    value={formData.current_carrier || ''} 
                    onValueChange={(value) => setFormData(prev => ({ ...prev, current_carrier: value }))}
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select current carrier" />
                    </SelectTrigger>
                    <SelectContent>
                      {CURRENT_CARRIER_OPTIONS.map(carrier => (
                        <SelectItem key={carrier} value={carrier}>{carrier}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  {errors.current_carrier && <p className="text-sm text-destructive">{errors.current_carrier}</p>}
                </div>
              </div>

              {/* Product Lines - REQUIRED */}
              <div className="space-y-2">
                <Label>Product Lines * <span className="text-xs text-muted-foreground">(Select all that apply)</span></Label>
                <div className="grid grid-cols-2 md:grid-cols-3 gap-2 p-3 border rounded-md">
                  {PRODUCT_LINE_OPTIONS.map(line => (
                    <div key={line} className="flex items-center space-x-2">
                      <Checkbox
                        id={`product-${line}`}
                        checked={formData.product_lines.includes(line)}
                        onCheckedChange={() => toggleProductLine(line)}
                      />
                      <Label htmlFor={`product-${line}`} className="cursor-pointer">{line}</Label>
                    </div>
                  ))}
                </div>
                {formData.product_lines.length > 0 && (
                  <div className="text-sm font-medium text-muted-foreground mt-2">
                    Lines: {formData.product_lines.length} 
                    {formData.product_lines.length === 1 ? ' (Monoline)' : ' (Bundle)'}
                  </div>
                )}
                {errors.product_lines && <p className="text-sm text-destructive">{errors.product_lines}</p>}
              </div>

              {/* Quick Action Status - REQUIRED */}
              <div className="space-y-2">
                <Label>Quick Action Status *</Label>
                <Select 
                  value={formData.quick_action_status} 
                  onValueChange={(value) => setFormData(prev => ({ ...prev, quick_action_status: value }))}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="Select status" />
                  </SelectTrigger>
                  <SelectContent>
                    {QUICK_ACTION_OPTIONS.map(option => (
                      <SelectItem key={option} value={option}>{option}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                {errors.quick_action_status && <p className="text-sm text-destructive">{errors.quick_action_status}</p>}
              </div>

              {/* Items Sold - REQUIRED when status is SOLD */}
              {(formData.quick_action_status ?? '').toUpperCase() === 'SOLD' && (
                <div className="space-y-2">
                  <Label htmlFor="items_sold">Items Sold *</Label>
                  <Input
                    id="items_sold"
                    type="number"
                    min={1}
                    max={10}
                    required
                    value={formData.items_sold ?? ''}
                    placeholder="Enter number of items sold"
                    onChange={(e) => {
                      const val = e.target.value;
                      setFormData((prev) => ({
                        ...prev,
                        items_sold: val === '' ? undefined : Math.max(1, Math.min(10, Number(val)))
                      }))
                    }}
                  />
                  {errors.items_sold && <p className="text-sm text-destructive">{errors.items_sold}</p>}
                </div>
              )}

              {/* Specific Notes on Call - OPTIONAL */}
              <div className="space-y-2">
                <Label htmlFor="notes">Specific Notes on Call</Label>
                <Textarea
                  id="notes"
                  value={formData.notes || ''}
                  onChange={(e) => setFormData(prev => ({ ...prev, notes: e.target.value || null }))}
                  placeholder="Enter any specific notes about the call..."
                  rows={3}
                />
              </div>

              {/* Hearsay - OPTIONAL */}
              <div className="flex items-center space-x-2">
                <Checkbox
                  id="hearsay"
                  checked={formData.opted_into_hearsay}
                  onCheckedChange={(checked) => 
                    setFormData(prev => ({ ...prev, opted_into_hearsay: checked as boolean }))
                  }
                />
                <Label htmlFor="hearsay">Opted into Hearsay</Label>
              </div>

              <div className="flex space-x-2 pt-2">
                <Button type="button" size="sm" onClick={handleSubmit}>
                  <Save className="h-4 w-4 mr-1" />
                  {editingIndex !== null ? 'Update' : 'Add'} QHH
                </Button>
                <Button type="button" variant="outline" size="sm" onClick={resetForm}>
                  Cancel
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* QHH List */}
      {quotedHouseholds.length > 0 && (
        <div className="space-y-3">
          {quotedHouseholds.map((qhh, index) => {
            const source = sources.find(s => s.id === qhh.lead_source_id)
            return (
              <Card key={index} className="p-4">
                <div className="flex items-start justify-between">
                  <div className="space-y-2 flex-1">
                    <div className="flex items-center space-x-3">
                      <h4 className="font-medium">Zip: {qhh.zip_code}</h4>
                      <Badge className={getStatusColor(qhh.quick_action_status)}>
                        {qhh.quick_action_status}
                      </Badge>
                      {qhh.is_bundle && (
                        <Badge variant="outline">Bundle</Badge>
                      )}
                    </div>
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm text-muted-foreground">
                      <div>
                        <span className="font-medium">Lines:</span> {qhh.lines_quoted}
                      </div>
                      <div>
                        <span className="font-medium">Premium:</span> ${qhh.quoted_premium.toFixed(2)}
                      </div>
                      <div>
                        <span className="font-medium">Source:</span> {source?.name || 'Unknown'}
                      </div>
                      {qhh.current_carrier && (
                        <div>
                          <span className="font-medium">Carrier:</span> {qhh.current_carrier}
                        </div>
                      )}
                      {(qhh.quick_action_status ?? '').toUpperCase() === 'SOLD' && qhh.items_sold && (
                        <div>
                          <span className="font-medium">Items Sold:</span> {qhh.items_sold}
                        </div>
                      )}
                      <div>
                        <span className="font-medium">Hearsay:</span> {qhh.opted_into_hearsay ? 'Yes' : 'No'}
                      </div>
                    </div>
                    <div className="text-sm">
                      <span className="font-medium text-muted-foreground">Products:</span> {qhh.product_lines.join(', ')}
                    </div>
                    {qhh.notes && (
                      <div className="text-sm">
                        <span className="font-medium text-muted-foreground">Notes:</span> {qhh.notes}
                      </div>
                    )}
                  </div>
                  {canEdit && (
                    <div className="flex space-x-1 ml-4">
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={() => startEdit(index)}
                      >
                        <Edit2 className="h-4 w-4" />
                      </Button>
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={() => onDelete(index)}
                      >
                        <X className="h-4 w-4" />
                      </Button>
                    </div>
                  )}
                </div>
              </Card>
            )
          })}
        </div>
      )}

      {totalQHH > 0 && quotedHouseholds.length === 0 && (
        <div className="text-center py-8 text-muted-foreground">
          <p>No quoted households entered yet.</p>
          <p className="text-sm">You need to enter {totalQHH} QHH details to match your source totals.</p>
        </div>
      )}
    </div>
  )
}